/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public class AdvantageForm extends javax.swing.JFrame {

    /**
     * Creates new form Removal
     */
    public AdvantageForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(450, 100));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jLabel1.setText("شماره سپرده");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jComboBox2.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "کوتاه مدت", "بلند مدت", "قرض الحسنه جاری", "قرض الحسنه پس انداز" }));

        jComboBox3.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jLabel4.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jLabel4.setText("نوع سپرده");

        jLabel5.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jLabel5.setText("کد نوع سپرده");

        jButton1.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jButton1.setText("واریز سود");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int getDays(String date){
    int year =1300 , month = 2 , day = 1;
    int count = 0;
    String[] Date = date.split("/");
    int days = Integer.parseInt(Date[2]);
    int months = Integer.parseInt(Date[1]);
    int years = Integer.parseInt(Date[0]);
    System.out.println(years + "/" + months + "/" + days);
    System.out.println(year + "/" + month + "/" + day);
    while(year!= years && month != months/* && day >= days*/ ){
       
        days++;
        count++;
        if(days == 30){
        
            days = 0;
            months++;
            
        }
        if(months == 12){
        
            months = 0;
            years++;
        
        }
    
    }
    
    
        return count;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       MessageBox Pm = new MessageBox();
       double Advantage = 0;
       boolean check = false;
       
        try {
            
            String Path = new File( "." ).getCanonicalPath(); 
            File fstream = new File(Path + "\\Deposit.txt");
              if(!fstream.exists()){
                
              Pm.setVisible(true);
              Pm.ShowMessage("فایل Deposit.txt پیدا نشد.");

            }
            else{
            BufferedReader br = new BufferedReader( new InputStreamReader( new FileInputStream(Path + "\\Deposit.txt"), "UTF8"));
            String strLine;
            StringBuilder fileContent = new StringBuilder();
            strLine = br.readLine();
            while (strLine != null) {
               
                String tokens[] = strLine.split("-");
                if (tokens.length > 0) {
                    
                if (tokens[0].equals(jTextField1.getText())&&tokens[1].equals(jComboBox2.getSelectedItem())&&tokens[2].equals(jComboBox3.getSelectedItem())) {
                        
                        if(tokens[1].equals("کوتاه مدت")){
                         
                            Advantage = (Double.parseDouble(tokens[7])*0.1*getDays(tokens[6]))/365;
                            double newMoney = Double.parseDouble(tokens[7]) + Advantage;
                            strLine = tokens[0] + "-" + tokens[1] + "-" + tokens[2] + "-"+ tokens[3] + "-" +  tokens[4] + "-" +  tokens[5] + "-" +  tokens[6] + "-" +  newMoney ;
                            fileContent.append(strLine);
                        }
                        check = true;
                                
                        strLine = null;
                    } else {
                       
                        strLine = br.readLine();
                    }
                }
                
            }
            
            br.close();
            FileWriter fstreamWrite = new FileWriter(Path + "\\Deposit.txt");
            
            BufferedWriter out = new BufferedWriter(fstreamWrite);
            out.write(fileContent.toString());
            
            out.close();
            
              Pm.setVisible(true);
            if(check == true)
            Pm.ShowMessage("عملیات با موفقیت انجام شد ."); 
            else
            Pm.ShowMessage("سپرده با این شماره یافت نشد.");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DepositInfoForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DepositInfoForm.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
