/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;

/**
 *
 * @author ASUS
 */
public class TransferForm extends javax.swing.JFrame {

    /**
     * Creates new form Advantage
     */
    public TransferForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(450, 100));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jLabel1.setText("شماره مشتری مبدا");

        jLabel2.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jLabel2.setText("شماره سپرده مبدا");

        jLabel3.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jLabel3.setText("شماره سپرده مقصد");

        jLabel4.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jLabel4.setText("مبلغ انتقالی");

        jLabel5.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jLabel5.setText("ریال");

        jButton1.setFont(new java.awt.Font("B Roya", 1, 14)); // NOI18N
        jButton1.setText("انتقال وجه");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)))
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        MessageBox Pm = new MessageBox();
        double Money ;
        boolean check1 = false;
        boolean check2 = true;
        String newLine1 = null;
        String newLine2 = null;

            
       try {
                String Path = new File( "." ).getCanonicalPath();
                FileInputStream fstream = new FileInputStream(Path + "\\Deposit.txt");
                BufferedReader br = new BufferedReader(new InputStreamReader(fstream,"UTF8"));
                String strLine;
                StringBuilder fileContent = new StringBuilder();
           
              while ((strLine = br.readLine()) != null) {
                
              
                String tokens[] = strLine.split("-");
                if (tokens.length > 0) {
                 
                    if(tokens[0].equals(jTextField2.getText())&&tokens[5].equals(jTextField1.getText())) {
                  
                        newLine1 = tokens[0] + "-" + tokens[1] + "-" + tokens[2] + "-" + tokens[3]+ "-" + tokens[4]+ "-" + tokens[5]+ "-" + tokens[6] + "-" + tokens[7];
                        check1 = true;  
                    }
    
                   else if(tokens[0].equals(jTextField3.getText())){
                        check2 = true;
                        newLine2 = tokens[0] + "-" + tokens[1] + "-" + tokens[2] + "-" + tokens[3]+ "-" + tokens[4]+ "-" + tokens[5]+ "-" + tokens[6] + "-" +  tokens[7];
                       
                    } 
                    
                   else{
                    fileContent.append(strLine);
                    fileContent.append("\n");
                       
                   }
                    
                    
                }
            }
              
              
            if(check1 && check2){
             
               
               String Data[] = newLine1.split("-");
               Money = Double.parseDouble(Data[7]);
            if(Money>=Double.parseDouble(jTextField4.getText())){
               Double newMoney = Money - Double.parseDouble(jTextField4.getText());
               newLine1 =  Data[0] + "-" + Data[1] + "-" + Data[2] + "-" + Data[3]+ "-" + Data[4]+ "-" + Data[5]+ "-" + Data[6] + "-" + newMoney; 
               fileContent.append(newLine1);
               fileContent.append("\n");
               Data = newLine2.split("-");
               Money = Double.parseDouble(Data[7]);
               newMoney = Money + Double.parseDouble(jTextField4.getText());
               newLine2 = Data[0] + "-" + Data[1] + "-" + Data[2] + "-" + Data[3]+ "-" + Data[4]+ "-" + Data[5]+ "-" + Data[6] + "-" + newMoney;
               fileContent.append(newLine2);
               fileContent.append("\n");
               Pm.setVisible(true);
               Pm.ShowMessage("عملیات با موفقیت انجام شد.");
               }
               
               else{
               Pm.setVisible(true);
               Pm.ShowMessage("موجودی حساب مبدا کافی نیست.");
               }
            }
             if(check1 == false){
               Pm.setVisible(true);
               Pm.ShowMessage("حساب مبدا یافت نشد.");
             }
             
             if(check2 == false){
               Pm.setVisible(true);
               Pm.ShowMessage("حساب مقصد یافت نشد.");
             }
            fstream.close();
            File file = new File(Path+"\\Deposit.txt");
            Writer fw = null;
            fw  = new OutputStreamWriter(new FileOutputStream(file, true), StandardCharsets.UTF_8);
            BufferedWriter bw = null;
            bw = new BufferedWriter(fw);
            bw.write(fileContent.toString());
            bw.close();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
